### ISSUE TITLE
Custom colour config

### ISSUE THREAD

**Issue by shtanton** [neoclide/coc-smartf#8]
This is a feature request, I'll write a PR for it if you think it's a good feature.

It would be nice if you could configure the colours (foreground and background).

I experimented a little bit and I think I could just add:
```
syntax off
hi Normal ctermfg=COLOUR
hi Conceal ctermfg=COLOUR
```
and then `syntax on` at the end.

I don't know a lot about how vim handles colours, I just did some poking around in the default colour scheme files. On my vim this worked just changing `ctermfg` but I'm guessing `guifg` also needs to be set.

**Comment by shtanton** [comment]
I just noticed you can do this with aucmds, I can still write a PR for this if you want but it's not necessary

**Comment by chemzqm** [comment]
Use autocmd is recommended

**Comment by shtanton** [comment]
The only problem is, running `syntax on` breaks the colours and underlining of the linter.

Any ideas why that is?

**Comment by chemzqm** [comment]
For some highlights to work, you may need run highlight command after `syntax on`, so I don't recommend to use command for temporary highlight change.
